---
- name: Install K3s
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }}; INSTALL_K3S_EXEC="server --no-deploy traefik" sh -s - --write-kubeconfig-mode 644
  register: k3sinstall
  changed_when: "'[INFO]  systemd: Starting k3s' in k3sinstall.stdout"
  # ok_when: "'[INFO]  No change detected so skipping service start' in k3sinstall.stdout"
  ignore_errors: true

- name: Open firewall ports for k3s Master
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 6443/tcp
    - 8472/udp
    - 10250/tcp
    - 51820/udp
    - 51821/udp

- name: Open firewall ports for k3s Worker
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 8472/udp
    - 10250/tcp
    - 51820/udp
    - 51821/udp

- name: Add Kubernetes repo
  ansible.builtin.shell: |
    cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
    [kubernetes]
    name=Kubernetes
    baseurl=https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/
    enabled=1
    gpgcheck=1
    gpgkey=https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/repodata/repomd.xml.key
    exclude=kubelet kubeadm cri-tools kubernetes-cni
    EOF

- name: Install kubectl
  ansible.builtin.dnf:
    name: kubectl
    state: present

- name: Configure kubectl
  ansible.builtin.shell: |
    mkdir ~/.kube
    sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    sudo chown $USER ~/.kube/config
    sudo chmod 600 ~/.kube/config
    export KUBECONFIG=~/.kube/config
  args:
    executable: /bin/bash
  ignore_errors: true
