---
- name: Install K3S
  ansible.builtin.import_tasks:
    file: install-rancher.yml
  tags: install

- name: Install MetalLB
  ansible.builtin.import_tasks:
    file: metallb.yml
  tags: metallb

- name: Install NGINX
  ansible.builtin.import_tasks:
    file: nginx.yml
  tags: nginx
...
