---
# Install MetalLB
- name: Create MetalLB k3s_namespace
  ansible.builtin.shell:
    cmd: "kubectl create namespace metallb-system"
  ignore_errors: True

- name: Install MetalLB
  ansible.builtin.shell:
    cmd: "kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml"

- name: Check if pods are running in the metallb-system namespace
  ansible.builtin.shell:
    cmd: "kubectl get pods -n metallb-system"
  register: check_metallb_pods
  until: check_metallb_pods.stdout.find('Running') != -1
  retries: 10
  delay: 10

# Configure MetalLB
- name: Place Metallb template
  ansible.builtin.template:
    src: "templates/metallb.yml.j2"
    dest: "/tmp/metallb.yml"
    mode: "0644"

- name: Place Metallb configmap template
  ansible.builtin.template:
    src: "templates/configmap.yml.j2"
    dest: "/tmp/configmap.yml"
    mode: "0644"

- name: Pause 15 sec so the next task will succeed
  ansible.builtin.pause:
    seconds: 15

- name: Apply MetalLB Manifest.
  ansible.builtin.shell:
    cmd: |
      kubectl apply -f /tmp/metallb.yml
  retries: 10
  delay: 10



- name: Apply MetalLB configmap Manifest.
  ansible.builtin.shell:
    cmd: |
      kubectl apply -f /tmp/configmap.yml


# Patch Service to Loadbalancer
- name: Patch Service to Loadbalancer
  ansible.builtin.shell:
    cmd: |
      kubectl patch svc kubernetes -n default -p '{"spec": {"type": "LoadBalancer"}}'

# - name: restart traefik
#  ansible.builtin.shell:
#    cmd: |
#      kubectl rollout restart deployment traefik -n kube-system