---
- name: Install NGINX ingress on k3s_namespace
  ansible.builtin.shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/cloud/deploy.yaml

- name: deploy template nginx loadbalancer
  ansible.buitlin.template:
    src: "templates/ingress-loadbalancer.yml.j2"
    dest: "/tmp/ingress-loadbalancer.yml"

- name: Deploy ngnix loadbalancer
  ansible.builtin.shell: |
    kubectl apply -f /tmp/ingress-loadbalancer.yml

